info:
  name: Auguste Lehuger
  tagline: Machine Learning Developer
  date_format: "%b %-d, %Y"

  social_links:
    email: auguste.lehuger@polytechnique.edu
    github:  alehuger
    linkedIn: in/alehuger # format: locale/username

title:
  Auguste Lehuger

description: 
  Personnal Blog

url:
  alehuger.github.io

author:
  Auguste Lehuger

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include: ['.htaccess']